"""Tokenization of internal entities before any send to the model.

Defense-in-depth complement to the gateway's pseudonymization: here, internal identifiers
(hosts, accounts, private IP addresses) never leave the platform. The model only sees
pseudonyms stable per hunt (`HOST-001`, `USER-002`, `IP-INT-003`), which preserves its
correlation ability across iterations without ever showing it a real value. The mapping
table lives within the hunt scope and serves three places:

- SIEM results tokenized before returning to the model (via minimization);
- queries generated by the model detokenized before execution on the SIEM;
- findings, conclusion and investigation thread rehydrated locally for the analyst.
"""

from __future__ import annotations

import ipaddress
import re
from typing import Any

_PREFIXES = {"host": "HOST", "user": "USER", "ip": "IP-INT", "data": "DATA"}

_TOKEN_RE = re.compile(r"\b(?:HOST|USER|IP-INT|DATA)-\d{3,}\b")
_IPV4_RE = re.compile(r"\b\d{1,3}(?:\.\d{1,3}){3}\b")


def find_tokens(text: str) -> list[str]:
    """Pseudonyms present in a text (HOST-001, USER-002, IP-INT-001, DATA-003)."""

    return _TOKEN_RE.findall(text)


def is_token(value: str) -> bool:
    """True if the value is already a pseudonym (do not re-tokenize it)."""

    return bool(_TOKEN_RE.fullmatch(value.strip()))


class TokenVault:
    """Mapping real value <-> pseudonym, stable for the duration of a hunt.

    The table appears in no API response: only the middleware traverses it, in both
    directions. It is persisted only in the hunt's resumption state, in the internal
    database, to allow continuing an interrupted loop; this state is purged at the hunt's
    conclusion and never leaves the platform.
    """

    def __init__(self, *, internal_suffixes: tuple[str, ...] = ()) -> None:
        self._by_value: dict[str, str] = {}
        self._by_token: dict[str, str] = {}
        self._extra_subs: dict[str, str] = {}
        self._loose: dict[str, str] = {}
        self._counters: dict[str, int] = {}
        suffixes = tuple(
            suffix.lower().lstrip(".") for suffix in internal_suffixes if suffix.strip()
        )
        self._host_pattern = (
            re.compile(
                r"\b[A-Za-z0-9][A-Za-z0-9_-]*(?:\.[A-Za-z0-9_-]+)*\.(?:"
                + "|".join(re.escape(suffix) for suffix in suffixes)
                + r")\b",
                re.IGNORECASE,
            )
            if suffixes
            else None
        )

    def snapshot(self) -> dict[str, Any]:
        """Serializable state of the table, for the hunt's resumption state."""

        return {
            "by_value": dict(self._by_value),
            "by_token": dict(self._by_token),
            "extra_subs": dict(self._extra_subs),
            "loose": dict(self._loose),
            "counters": dict(self._counters),
        }

    def load(self, payload: dict[str, Any]) -> None:
        """Restore a saved table; the internal suffixes come from the constructor."""

        self._by_value = {str(k): str(v) for k, v in (payload.get("by_value") or {}).items()}
        self._by_token = {str(k): str(v) for k, v in (payload.get("by_token") or {}).items()}
        self._extra_subs = {str(k): str(v) for k, v in (payload.get("extra_subs") or {}).items()}
        self._loose = {str(k): str(v) for k, v in (payload.get("loose") or {}).items()}
        self._counters = {str(k): int(v) for k, v in (payload.get("counters") or {}).items()}

    def token_for(self, kind: str, value: str) -> str:
        cleaned = value.strip()
        if not cleaned or kind not in _PREFIXES:
            return value
        key = cleaned.lower()
        token = self._by_value.get(key)
        if token is None:
            count = self._counters.get(kind, 0) + 1
            self._counters[kind] = count
            token = f"{_PREFIXES[kind]}-{count:03d}"
            self._by_value[key] = token
            self._by_token[token] = cleaned
        return token

    def alias(self, variant: str, token: str) -> None:
        """Attach a derived form (local part of an email, `first.last`, URL encoding) to an
        already-set pseudonym. Replaced without a word-boundary requirement, to reach
        names buried in a path or an identifier; detokenization restores the canonical
        form of the pseudonym."""

        cleaned = variant.strip()
        key = cleaned.lower()
        if len(cleaned) >= 3 and token in self._by_token and key not in self._by_value:
            self._loose[key] = token

    def register_substitution(self, value: str, replacement: str) -> None:
        """Record a sensitive value to replace everywhere, including in free text.

        Used for masked personal fields (email, name): the same value encountered in a
        bulk "additional" field will get the same mask, whatever the column order.
        Irreversible: does not enter the detokenization table."""

        cleaned = value.strip()
        if cleaned and cleaned.lower() not in self._by_value:
            self._extra_subs[cleaned] = replacement

    def tokenize_text(self, text: str) -> str:
        """Replace in free text the already-known values (hosts, accounts, masked personal
        values), private IPs and hosts with an internal DNS suffix."""

        if not text:
            return text
        subs = {**self._by_value, **self._extra_subs}
        for key in sorted(subs, key=len, reverse=True):
            pattern = re.compile(rf"(?<![\w.-]){re.escape(key)}(?![\w-])", re.IGNORECASE)
            text = pattern.sub(subs[key], text)
        for key in sorted(self._loose, key=len, reverse=True):
            text = re.compile(re.escape(key), re.IGNORECASE).sub(self._loose[key], text)
        if self._host_pattern is not None:
            text = self._host_pattern.sub(
                lambda match: self.token_for("host", match.group(0)), text
            )
        return _IPV4_RE.sub(self._replace_if_private, text)

    def detokenize_text(self, text: str) -> str:
        """Restore the real values. Called only for internal use: query going to a SIEM,
        report, investigation thread."""

        if not text:
            return text
        return _TOKEN_RE.sub(lambda match: self._by_token.get(match.group(0), match.group(0)), text)

    def _replace_if_private(self, match: re.Match[str]) -> str:
        candidate = match.group(0)
        try:
            address = ipaddress.ip_address(candidate)
        except ValueError:
            return candidate
        if address.is_private or address.is_loopback or address.is_link_local:
            return self.token_for("ip", candidate)
        return candidate
