"""Generates the knowledge/{sentinel,defender,secops}.md cards from the xlsx inventories.

The cards describe the REAL environment (tables, columns, log types and fields that are
actually populated) so the agent never generates a query against a nonexistent table or
field. Re-run after each inventory update:

    .venv/bin/python scripts/generate_knowledge.py

The xlsx files stay out of the repository; the generated cards, however, are versioned.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
BUDGET = 8_500
_STAMP = datetime.now(UTC).strftime("%Y-%m-%d")

SENTINEL_PRIORITY = (
    "SigninLogs",
    "AADNonInteractiveUserSignInLogs",
    "AADServicePrincipalSignInLogs",
    "AuditLogs",
    "IdentityInfo",
    "DeviceFileEvents",
    "CloudAppEvents",
    "OfficeActivity",
    "MicrosoftGraphActivityLogs",
    "AlertEvidence",
    "AlertInfo",
    "SecurityIncident",
    "SecurityAlert",
)
NOTABLE_ABSENT = (
    "SecurityEvent",
    "DnsEvents",
    "CommonSecurityLog",
    "Syslog",
    "DeviceProcessEvents",
    "DeviceNetworkEvents",
    "Event",
    "W3CIISLog",
)


def _rows(sheet: Any) -> Any:
    rows = sheet.iter_rows(values_only=True)
    next(rows, None)
    for row in rows:
        if row and row[0] is not None:
            yield row


def _fmt_part(value: Any) -> str:
    """Volume share as an approximate percentage: the order of magnitude is enough to
    decide the query strategy (filter tightly on a large table, read everything on a small
    one)."""

    try:
        percent = float(value) * 100
    except (TypeError, ValueError):
        return "unknown share"
    if percent >= 10:
        return f"~{percent:.0f}% of volume"
    if percent >= 1:
        return f"~{percent:.0f}%"
    if percent >= 0.1:
        return f"~{percent:.1f}%"
    return "< 0.1%"


def generate_sentinel() -> str:
    workbook = load_workbook(
        ROOT / "sentinel_inventory_tables.xlsx", read_only=True, data_only=True
    )
    volumes = {str(row[0]): row[3] for row in _rows(workbook["Volumes 30d"])}
    tables = [str(row[0]) for row in _rows(workbook["Tables"])]
    columns: dict[str, list[str]] = defaultdict(list)
    for row in _rows(workbook["Columns"]):
        columns[str(row[0])].append(str(row[1]))
    workbook.close()

    ordered = sorted(tables, key=lambda t: -float(volumes.get(t) or 0))
    absent = [name for name in NOTABLE_ABSENT if name not in set(tables)]
    usage_only = [name for name in volumes if name not in set(tables)]

    lines = [
        f"<!-- Generated by scripts/generate_knowledge.py on {_STAMP}. Do not edit. -->",
        "Real inventory of the Log Analytics workspace. The tables below are the",
        "ONLY ones that contain data: NEVER query a table absent from this",
        "list, the query will return nothing"
        + (f" (in particular: {', '.join(absent)} do not exist here)." if absent else "."),
        "Time column: `TimeGenerated`. Columns common to all tables:",
        "`TimeGenerated`, `TenantId`, `Type`.",
        "",
        f"**Available tables ({len(tables)}), share of volume over 30 d:**",
        "",
    ]
    for name in ordered:
        lines.append(
            f"- `{name}` ({len(columns.get(name, []))} col, {_fmt_part(volumes.get(name))})"
        )
    if usage_only:
        lines += [
            "",
            "Tables billed but outside the exported schema (verify before use): "
            + ", ".join(f"`{name}`" for name in sorted(usage_only)),
        ]
    lines += [
        "",
        "**Exact columns of the priority tables** (only these columns exist):",
        "",
    ]

    body = "\n".join(lines)
    detail_order = [t for t in SENTINEL_PRIORITY if t in columns] + [
        t for t in ordered if t not in SENTINEL_PRIORITY
    ]
    for name in detail_order:
        entry = f"- `{name}` : " + ", ".join(columns[name])
        if len(body) + len(entry) + 1 > BUDGET:
            break
        body += "\n" + entry
    return body + "\n"


def generate_defender() -> str:
    workbook = load_workbook(
        ROOT / "defender_inventory_tables.xlsx", read_only=True, data_only=True
    )
    volumes = {str(row[0]): row[2] for row in _rows(workbook["Volumes 7d"])}
    tables = [str(row[0]) for row in _rows(workbook["Tables"])]
    columns: dict[str, list[str]] = defaultdict(list)
    for row in _rows(workbook["Columns"]):
        columns[str(row[0])].append(str(row[1]))
    workbook.close()

    ordered = sorted(tables, key=lambda t: -float(volumes.get(t) or 0))
    lines = [
        f"<!-- Generated by scripts/generate_knowledge.py on {_STAMP}. Do not edit. -->",
        "Real inventory of the Defender tenant (Advanced Hunting). The tables below",
        "are the only ones populated, and for each one ONLY the listed columns are",
        "actually filled: use neither a table nor a column outside this list.",
        "Time column: `Timestamp`.",
        "",
        f"**Populated tables and columns ({len(tables)}, share of volume over 7 d):**",
        "",
    ]
    body = "\n".join(lines)
    for name in ordered:
        part = _fmt_part(volumes.get(name))
        entry = f"- `{name}` ({part}) : " + ", ".join(columns.get(name, []))
        if len(body) + len(entry) + 1 > BUDGET:
            body += f"\n- `{name}` ({part})"
            continue
        body += "\n" + entry
    return body + "\n"


def generate_secops() -> str:
    workbook = load_workbook(ROOT / "secops_inventory_udm.xlsx", read_only=True, data_only=True)
    log_types = []
    for row in _rows(workbook["Log types"]):
        log_types.append(
            {
                "name": str(row[0]),
                "events": float(row[1] or 0),
                "part": row[2],
                "products": str(row[3] or ""),
                "event_types": str(row[4] or ""),
            }
        )
    fields = {
        str(row[0]): {"filled": str(row[3] or ""), "never": str(row[5] or "")}
        for row in _rows(workbook["Fields used"])
    }
    enums = {
        str(row[0]): {
            "direction": str(row[3] or ""),
            "action": str(row[5] or ""),
            "severity": str(row[6] or ""),
        }
        for row in _rows(workbook["Enumeration values"])
    }
    workbook.close()

    log_types.sort(key=lambda item: -item["events"])
    lines = [
        f"<!-- Generated by scripts/generate_knowledge.py on {_STAMP}. Do not edit. -->",
        "Real inventory of the SecOps tenant (UDM). The log types below are the only",
        "ones populated. For each: only the fields listed as filled carry",
        "data — a filter on a 'never filled' field will NEVER match.",
        "Filter first by `metadata.event_type` (real values per log type below)",
        "or `metadata.log_type`.",
        "",
        f"**Log types ({len(log_types)}), by volume:**",
        "",
    ]
    body = "\n".join(lines)
    for item in log_types:
        name = item["name"]
        part = _fmt_part(item["part"])
        entry = [f"- `{name}` ({part}) — products: {item['products']}"]
        entry.append(f"  event_types: {item['event_types']}")
        detail = fields.get(name)
        if detail and detail["filled"]:
            entry.append(f"  filled fields: {detail['filled']}")
        if detail and detail["never"]:
            entry.append(f"  never filled: {detail['never']}")
        enum = enums.get(name)
        if enum and (enum["action"] or enum["direction"]):
            entry.append(
                "  real values: action="
                + (enum["action"] or "-")
                + " · direction="
                + (enum["direction"] or "-")
                + " · severity="
                + (enum["severity"] or "-")
            )
        block = "\n".join(entry)
        if len(body) + len(block) + 1 > BUDGET:
            body += f"\n- `{name}` ({part})"
            continue
        body += "\n" + block
    return body + "\n"


def main() -> int:
    generated = {
        "sentinel": generate_sentinel,
        "defender": generate_defender,
        "secops": generate_secops,
    }
    for name, builder in generated.items():
        try:
            content = builder()
        except FileNotFoundError as error:
            print(f"{name}: inventory missing ({error.filename}), card unchanged")
            continue
        target = ROOT / "knowledge" / f"{name}.md"
        target.write_text(content, encoding="utf-8")
        print(f"{name}: {len(content)} characters -> {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
